.TH ${PROJECT_NAME} 1 "${PROJECT_BUILD_TIMESTAMP_DISPLAY}" "${PROJECT_NAME} ${PROJECT_VERSION}"

.SH NAME
${PROJECT_NAME} \- Manage multiple installed Qt versions

.SH SYNOPSIS
.SY ${PROJECT_NAME}
.B list
[\-\-path \c
.I PATH\c
] \.\.\.
.YS
.SY ${PROJECT_NAME}
.B choose
.I PREFIX
.YS
.SY ${PROJECT_NAME}
\-h|\-\-help
.YS
.SY ${PROJECT_NAME}
\-v|\-\-version
.YS

.SH DESCRIPTION
.P
.B ${PROJECT_NAME}
helps update system environment variables to reflect a chosen installation of Qt.

.SS list
.P
Lists the Qt installations found on the system. By default, this will look in the following directories:

.IP
.I
/usr
(default path for distro package managers)
.IP
.I
/usr/local
.IP
.I
\(ti/Qt
(default path for official Qt installer)

.P
Use the
.B --path
option to add additional paths to search. Both POSIX prefixes and official Qt Installer directories are supported.

.SS choose
.P
Update system environment variables to use the Qt installation in the given prefix.

.P
The following variables are updated:

.RS
.TP 12
.I Qt6_DIR
Path to the chosen Qt's CMake package file

.TP
.I Qt_DIR
Same as Qt6_DIR

.TP
.I QT_ROOT_DIR
Qt install prefix

.TP
.I PATH
Updates \(ti/.bash_profile to prefix Qt's executable directories to the PATH.
.RE

.SH EXAMPLES
.P
Find Qt installations on the system:
.IP
.EX
$ ${PROJECT_NAME} list
+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| Active | Version |\ \ \ \ \ \ \ \ \ \ \ \ Path \ \ \ \ \ \ \ \ \ \ \ |
+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
|\ \ \ \ \ \ \ \ | 6.8.3 \ \ | /home/user/Qt/6.8.3/gcc_64 |
+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| Active | 6.10.3 \ | /usr \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ |
+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
.EE
.P
Select the desired Qt:
.IP
.EX
$ ${PROJECT_NAME} choose /home/user/Qt/6.8.3/gcc_64
Choosing Qt at /home/user/Qt/6.8.3/gcc_64
An environment variable has changed. You may need to log out and back in for this change to take effect in all programs.
.EE

.SH LICENSE
.P
Copyright (C) ${PROJECT_BUILD_TIMESTAMP_YEAR} ${PROJECT_AUTHOR}

.P
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

.P
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

.P
You should have received a copy of the GNU General Public License
along with this program.  If not, see
.UR https://www.gnu.org/licenses/
.UE \c
\&.
